use anyhow::{Context, Result};
use prism_common::digest::Digest;
use prism_da::LightClientDataAvailabilityLayer;
use prism_errors::{DataAvailabilityError, GeneralError};
use prism_keys::VerifyingKey;
use std::{self, sync::Arc};
use tokio::sync::broadcast;

#[cfg(target_arch = "wasm32")]
use wasm_bindgen_futures::spawn_local;

#[cfg(not(target_arch = "wasm32"))]
use tokio::task::spawn;

#[allow(unused_imports)]
use sp1_verifier::Groth16Verifier;

#[cfg(not(target_arch = "wasm32"))]
pub type LightClientDataAvailabilityLayerType =
    Arc<dyn LightClientDataAvailabilityLayer + Send + Sync>;

#[cfg(target_arch = "wasm32")]
pub type LightClientDataAvailabilityLayerType = Arc<dyn LightClientDataAvailabilityLayer>;

pub struct LightClient {
    pub da: LightClientDataAvailabilityLayerType,
    /// The public key of the prover, used for verifying the signature of the epochs.
    pub prover_pubkey: Option<VerifyingKey>,
    /// The verification key for the SP1 program, generated by `vk.bytes32()`.
    pub sp1_vkey: String,
    /// The height to start syncing from.
    pub start_height: u64,
}

#[allow(dead_code)]
impl LightClient {
    pub fn new(
        da: LightClientDataAvailabilityLayerType,
        start_height: u64,
        prover_pubkey: Option<VerifyingKey>,
        sp1_vkey: String,
    ) -> LightClient {
        LightClient {
            da,
            sp1_vkey,
            prover_pubkey,
            start_height,
        }
    }

    pub async fn run(self: Arc<Self>) -> Result<()> {
        // start listening for new headers to update sync target
        self.da
            .start()
            .await
            .map_err(|e| DataAvailabilityError::InitializationError(e.to_string()))
            .context("Failed to start DataAvailabilityLayer")?;

        self.sync_loop()
            .await
            .map_err(|e| GeneralError::InitializationError(e.to_string()))
            .context("Sync loop failed")
    }

    async fn process_heights(&self, mut current_position: u64) {
        let mut height_rx = self.da.subscribe_to_heights();

        loop {
            match height_rx.recv().await {
                Ok(target) => {
                    for i in current_position..target {
                        match self.da.get_finalized_epoch(i + 1).await {
                            Ok(Some(finalized_epoch)) => {
                                if let Some(pubkey) = &self.prover_pubkey {
                                    match finalized_epoch.verify_signature(pubkey.clone()) {
                                        Ok(_) => trace!(
                                            "valid signature for epoch {}",
                                            finalized_epoch.height
                                        ),
                                        Err(e) => {
                                            panic!("invalid signature in epoch {}: {:?}", i, e)
                                        }
                                    }
                                }

                                let public_values = match &finalized_epoch.proof {
                                    #[cfg(target_arch = "wasm32")]
                                    proof => proof.as_slice(),
                                    #[cfg(not(target_arch = "wasm32"))]
                                    proof => proof.public_values.as_slice(),
                                };

                                if public_values.len() < 64 {
                                    panic!(
                                        "public_values length is less than 64 bytes in epoch {}",
                                        finalized_epoch.height
                                    );
                                }

                                let mut slice = [0u8; 32];
                                slice.copy_from_slice(&public_values[..32]);
                                let proof_prev_commitment: Digest = Digest::from(slice);
                                let mut slice = [0u8; 32];
                                slice.copy_from_slice(&public_values[32..64]);
                                let proof_current_commitment: Digest = Digest::from(slice);

                                if finalized_epoch.prev_commitment != proof_prev_commitment
                                    || finalized_epoch.current_commitment
                                        != proof_current_commitment
                                {
                                    error!(
                                        "Commitment mismatch:
                                        prev_commitment: {:?}, proof_prev_commitment: {:?},
                                        current_commitment: {:?}, proof_current_commitment: {:?}",
                                        finalized_epoch.prev_commitment,
                                        proof_prev_commitment,
                                        finalized_epoch.current_commitment,
                                        proof_current_commitment
                                    );
                                    panic!(
                                        "Commitment mismatch in epoch {}",
                                        finalized_epoch.height
                                    );
                                }

                                // SNARK verification
                                #[cfg(feature = "mock_prover")]
                                info!("mock_prover is activated, skipping proof verification");
                                #[cfg(not(feature = "mock_prover"))]
                                match Groth16Verifier::verify(
                                    &finalized_epoch.proof,
                                    public_values,
                                    &self.sp1_vkey,
                                    &sp1_verifier::GROTH16_VK_BYTES,
                                ) {
                                    Ok(_) => info!(
                                        "zkSNARK for epoch {} was validated successfully",
                                        finalized_epoch.height
                                    ),
                                    Err(err) => panic!(
                                        "failed to validate epoch at height {}: {:?}",
                                        finalized_epoch.height, err
                                    ),
                                }
                            }
                            Ok(None) => {
                                debug!("no finalized epoch found at height: {}", i + 1);
                            }
                            Err(e) => debug!("light client: getting epoch: {}", e),
                        };
                    }
                    current_position = target;
                }
                Err(broadcast::error::RecvError::Closed) => {
                    error!("Height channel closed unexpectedly");
                    break;
                }
                Err(broadcast::error::RecvError::Lagged(skipped)) => {
                    warn!("Lagged behind by {} messages", skipped);
                }
            }
        }
    }

    #[cfg(not(target_arch = "wasm32"))]
    async fn sync_loop(self: Arc<Self>) -> Result<(), tokio::task::JoinError> {
        info!("starting SNARK sync loop");
        let light_client = self.clone();
        let start_height = self.start_height;

        spawn(async move {
            light_client.process_heights(start_height).await;
        })
        .await
    }

    #[cfg(target_arch = "wasm32")]
    async fn sync_loop(self: Arc<Self>) -> Result<()> {
        info!("starting SNARK sync loop");
        let start_height = self.start_height;
        let light_client = self.clone();

        spawn_local(async move {
            light_client.process_heights(start_height).await;
        });

        Ok(())
    }
}
