[package]
name = "prism-nova"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
# num = { workspace = true }
# rand = { workspace = true }
# ff = { workspace = true }
# thiserror = { workspace = true }
# celestia-types = { workspace = true }
# anyhow = { workspace = true }
# jmt = { workspace = true }
# bellpepper-core = { workspace = true }
# bellpepper = { workspace = true }
# arecibo = { workspace = true }
# itertools = { workspace = true }
# prism-common = { workspace = true, features = ["test_utils"] }
