[package]
name = "prism-groth16"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
# bellman = { workspace = true }
# bls12_381 = { workspace = true }
# rand = { workspace = true }
# hex = { workspace = true }
# ff = { workspace = true }
# tracing = { workspace = true }
# indexed-merkle-tree = { workspace = true }
# anyhow = { workspace = true }
# prism-common = { workspace = true }
# prism-errors = { workspace = true }
