[package]
name = "prism-sp1"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
prism-common = { workspace = true }
prism-tree = { workspace = true }
sp1-zkvm = { workspace = true, features = ["verify"]}
sp1-verifier = { workspace = true }
sha2 = { workspace = true }

[[bin]]
name = "base_prover"
path = "src/bin/base_prover.rs"

[[bin]]
name = "recursive_prover"
path = "src/bin/recursive_prover.rs"
