# Taken from eigerco/lumina

# A dockerfile for the celestia bridge node in DA layer
# Based on:
# https://github.com/celestiaorg/celestia-node/blob/main/Dockerfile
FROM celestia-node:latest

ENV CELESTIA_HOME=/root

#RUN apk update && apk add --no-cache bash jq

# Copy in the binary
# COPY celestia-node.docker /bin/celestia
# COPY celestia-node.docker /bin/cel-key

COPY ./run-lightnode.sh /opt/entrypoint.sh
RUN chmod +x /opt/entrypoint.sh

EXPOSE 2121 26658

CMD /opt/entrypoint.sh
