services:
  validator:
    image: validator
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile.validator
    environment:
      # provide amount of bridge nodes to provision (default: 1)
      - BRIDGE_COUNT=2
      - LIGHT_COUNT=1
    volumes:
      - credentials:/credentials
      - shared:/shared

  bridge-0:
    image: bridge
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile.bridge
    environment:
      # provide an id for the bridge node (default: 0)
      # each node should have a next natural number starting from 0
      - NODE_ID=0
      # setting SKIP_AUTH to true disables the use of JWT for authentication
      - SKIP_AUTH=true
      # this must match the service name in the docker-compose.yml file
      # used for the trusted peers string for the light node
      - CONTAINER_NAME=bridge-0
    ports:
      - 26658:26658
    volumes:
      - credentials:/credentials
      - shared:/shared

  bridge-1:
    image: bridge
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile.bridge
    environment:
      # provide an id for the bridge node (default: 0)
      # each node should have a next natural number starting from 0
      - NODE_ID=1
      # setting SKIP_AUTH to true disables the use of JWT for authentication
      - SKIP_AUTH=true
      # this must match the service name in the docker-compose.yml file
      # used for the trusted peers string for the light node
      - CONTAINER_NAME=bridge-1
    ports:
      - 36658:26658
    volumes:
      - credentials:/credentials
      - shared:/shared

  light-0:
    image: light
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile.lightnode
    environment:
      # provide an id for the light node (default: 0)
      # each node should have a next natural number starting from 0
      - NODE_ID=0
      # setting SKIP_AUTH to true disables the use of JWT for authentication
      - SKIP_AUTH=true
      # depending on the number of bridge nodes, provide the count
      # is used for the trusted peers string for the light node
      - BRIDGE_COUNT=2
    ports:
      - 46658:26658
    volumes:
      - credentials:/credentials
      - shared:/shared

volumes:
  # local volume where node's credentials can persist
  credentials:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "./credentials"
  # a temporary fs where the nodes share data
  shared:
    driver_opts:
      type: tmpfs
      device: tmpfs
